- name: Fetch TryHackMe Badge
  uses: DhanushNehru/tryhackme-badge-action-workflow@v1.0
  with:
    image_path: './assets/tryhackme-badge.png'
    username: 'nicocorbeau'
    user_id: '3623406'
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
